### ISSUE TITLE
id required in body SNS message (sending results to client via WebSockets)

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-ne-classic-package-provider#74]
As noted by @lennym / @tomgco the `id` is required in the Object that is sent via SNS.

*I* removed it: https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/71/files#diff-bbf35676791c94b15209e00cc3641ab3L20 

It was *unclear* from https://github.com/numo-labs/lambda-search-result-handler/blob/956e84b42531a09f243c68a23f385ac2a2f1bd67/README.md that it was still required...

however in retrospect I should have checked the `pushToSNSTopic` method in https://github.com/numo-labs/aws-lambda-helper/blob/a03f3226f390ee4f54329ee7b580054c36d1f538/lib/index.js#L284

At the moment it's not *possible* to run a complete **e2** test that would prevent this kind of *regression* from occurring. see: https://github.com/numo-labs/lambda-ne-classic-package-provider/issues/72

@lennym is busy adding `id` back in. 👍  (*thanks*)

**Comment by lennym** [comment]
The underlying issue was fixed at https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/73

I have some ongoing work to validate the parameters sent to the client in https://github.com/numo-labs/aws-lambda-helper/blob/master/lib/index.js#L363 to ensure that an id property is present and fail early if it is not.

**Comment by nelsonic** [comment]
Thanks @lennym  👍

**Comment by lennym** [comment]
See https://github.com/numo-labs/aws-lambda-helper/pull/56

**Comment by nelsonic** [comment]
Thanks for updating that @lennym 👍
